apiVersion: v1
kind: ConfigMap
metadata:
  name: mongocfg
data:
  # property-like keys; each key maps to a simple value
  DB_HOST: "100.69.218.45"
  DB_PORT: "27017"  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: irssvc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irssvc1
  template:
    metadata:
      labels:
        app: irssvc1
    spec:
      containers:
        - name: service1
          image: tadeosmlk/irssvc1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongocfg          
                  key: DB_HOST               
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongocfg
                  key: DB_PORT              		
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: irssvc1
spec:
  type: LoadBalancer
  selector:
    app: irssvc1
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31082
